import assert from 'node:assert/strict';
import { cellar_raid } from './app/systems/cellar_raid.js';
import { createCombat } from './combat.js';
import { spawnMonster } from './actor.js';
import { RAID } from '../mmo/cellar_raid_rules.js';
import { applyRaidReward, hydrateRaidRewards, prepareRaidReward, recordRaidClaim } from './cellar_rewards.js';
import { createState } from './state.js';
import { createCorpseLoot } from './corpse_loot.js';
const player = spawnMonster('ironGolem', { x: RAID.x + 13, y: 0, z: RAID.z });
player.faction = 'player';
player.kind = 'player';
const combat = createCombat({ rng: () => 0 });
const messages = [], opened = [], accepted = [];
const state = createState({ storage: null });
let receive, registered;
let animate = 0;
const model = { group: {}, setDead() { }, update() { animate++; }, hit: {} };
const runtime = { inDungeon: true, dungeonScene: { raid: { ...RAID, model } }, dungeonLayout: () => ({ siteId: 'oldcellars', level: 8, name: 'The buried cathedral' }) };
const targeting = { current: null, set(a) { this.current = a; }, clear() { this.current = null; } };
const corpseLoot = createCorpseLoot({ at: () => player.pos });
const deps = { world: { runtime }, player: { actor: player, rig: { pos: player.pos }, levels: { award() { } } }, net: { connected: true, layer: () => RAID.layer, instance: () => 'client-test', onMessage(fn) { receive = fn; return () => { }; }, send(m) { messages.push(m); } }, combat: { combat, targeting, monsters: { registerExternalTarget(a) { registered = a; return () => { registered = null; }; } }, swingAt(a, now) { return combat.queueSwing(player, a, { now }); } }, abilities: { effects: { burst() { } }, abilities: {} }, inventory: { corpseLoot, takeLoot(items, gold) { accepted.push({ items, gold }); return { items, gold }; } }, ui: { windows: { open(id, extra) { opened.push({ id, corpse: extra.corpse }); }, close() { } } } };
const ctx = { get: k => deps[k], hud: { toast() { } }, state, frame: { now: 10000, nowS: 10, dt: .016 } };
const sys = cellar_raid.create(ctx);
receive({ t: 'raid', now: Date.now(), run: 1, hp: RAID.maxHealth, status: 'fighting', phase: 1 });
sys.step(ctx.frame);
assert(registered);
sys.toggle();
sys.step(ctx.frame);
combat.update(.3, 10300);
assert(messages.some(m => m.t === 'raidStrike' && m.kind === 'melee' && m.damage > 0));
assert.equal(sys.actor.health, RAID.maxHealth, 'server-owned health does not decrement locally');
const n = messages.length;
combat.queueSpell(player, { base: [20, 20], damageType: 'fire' }, sys.actor, { now: 11000 });
combat.update(.3, 11400);
assert(messages.length > n && messages.at(-1).kind === 'spell');
combat.hurt(sys.actor, 100, { killer: player, now: 12000 });
assert.equal(messages.at(-1).damage, 100);
assert.equal(sys.actor.health, RAID.maxHealth);
assert.doesNotThrow(() => combat.applyFall(sys.actor, 20, 12000));
const before = player.health;
receive({ t: 'raidDamage', event: '1:3', damage: 20, name: 'Test' });
receive({ t: 'raidDamage', event: '1:3', damage: 20, name: 'Test' });
assert.equal(player.health, before - 20, 'damage replay ignored');
receive({ t: 'raid', now: Date.now(), run: 1, hp: RAID.maxHealth - 50, status: 'shielded', phase: 1 });
sys.step(ctx.frame);
assert.equal(sys.actor.health, RAID.maxHealth - 50);
const count = messages.length;
combat.hurt(sys.actor, 100, { killer: player });
assert.equal(messages.length, count, 'shield refuses submissions');
// A server reward is first a durable, reopenable corpse claim. Invalid wire
// data does not create a target; being outside reach does not discard one.
const raidReward = { t: 'raidReward', run: 7, gold: 2500, base: 'starfall_ore', count: 36 };
receive({ ...raidReward, count: 35 });
assert.equal(opened.length, 0, 'invalid reward cannot open a claim panel');
receive(raidReward);
const corpse = opened.at(-1).corpse;
assert(corpse && corpse === sys.rewardCorpse && corpse.loot.items[0].count === 36, 'reward opens as the one durable corpse');
assert.equal(corpseLoot.takeAll(corpse).ok, false, 'a far player cannot claim through the auto-opened panel');
player.pos.x = RAID.x; player.pos.z = RAID.z;
assert.equal(sys.openReward(), true, 'the saved reward can reopen after closing its panel');
assert.equal(opened.at(-1).corpse, corpse, 'reopen retains the same corpse record');
receive(raidReward);
assert.equal(opened.at(-1).corpse, corpse, 'server replay refreshes the same claim instead of a stale duplicate');
assert.equal(corpse.loot.items[0].count, 36, 'a replay does not multiply current reward contents');
const claimed = corpseLoot.takeAll(corpse);
assert.equal(claimed.ok && claimed.emptied, true, 'the full accepted claim succeeds before the corpse closes');
assert.equal(accepted.length, 1, 'one inventory transaction receives the completed reward');
assert.deepEqual(state.character.raidRewards['client-test:7'], { gold: true, ore: 36, xp: true, pending: false });
receive(raidReward);
assert.equal(corpse.active, false, 'completed reward replay retires its prior corpse');
assert.equal(corpseLoot.takeAll(corpse).ok, false, 'completed checkpoint cannot issue inventory changes again');
receive({ ...raidReward, run: 8 });
const exiting = sys.rewardCorpse;
assert(exiting?.active, 'a later pending reward is claimable before leaving the layer');
runtime.dungeonScene = null;
sys.step(ctx.frame);
assert.equal(registered, null);
assert.equal(exiting.active, false, 'leaving the raid layer retires a pending reward corpse');
assert.equal(corpseLoot.takeAll(exiting).ok, false, 'a retired checkpoint cannot make an inventory transaction');
assert.equal(accepted.length, 1, 'layer exit did not hand out a pending reward');
sys.dispose();
assert(animate > 0);
const gold = state.coins;
const reward = { run: 1, gold: 2500, base: 'starfall_ore', count: 36 };
let saveCount = 0;
const oldSave = state.save;
state.save = () => { saveCount++; return oldSave(); };
assert(applyRaidReward(state, reward, 'raid-test').complete);
assert.equal(state.coins, gold + 2500);
assert.equal(applyRaidReward(state, reward, 'raid-test').changed, false);
assert.equal(saveCount, 1);
assert.deepEqual(hydrateRaidRewards(state.character.raidRewards)['raid-test:1'], { gold: true, ore: 36, xp: false, pending: false });
const partial = { character: {}, coins: 0, addMaterial: n => ({ added: 0 }), save() { } };
assert.equal(applyRaidReward(partial, reward, 'raid-test').complete, false);
partial.addMaterial = () => ({ added: 12 });
applyRaidReward(partial, reward, 'raid-test');
applyRaidReward(partial, reward, 'raid-test');
assert(applyRaidReward(partial, reward, 'raid-test').complete);
assert.equal(partial.coins, 2500);
const staged = { character: {}, save() {} };
const pending = prepareRaidReward(staged, reward, 'raid-pending');
assert.equal(pending.pending.ore, 36, 'the reward is durable before the window opens');
assert.equal(recordRaidClaim(staged, reward, 'raid-pending', { gold: 2500, items: [{ base: 'starfall_ore', count: 12 }] }).complete, false);
assert.equal(prepareRaidReward(staged, reward, 'raid-pending').pending.ore, 24, 'a replay only shows the unclaimed stack');
assert(recordRaidClaim(staged, reward, 'raid-pending', { items: [{ base: 'starfall_ore', count: 24 }] }).complete);
assert.equal(hydrateRaidRewards({ old: { gold: true, ore: 36 } }).old, undefined, 'bad checkpoint keys stay ignored');
assert.equal(hydrateRaidRewards({ 'old:1': { gold: true, ore: 36 } })['old:1'].xp, true, 'old completed rewards do not grant retroactive XP');
console.log('Raid client passed: actual frame clock, melee/spell/flat-damage routing, authoritative health, damage replay, shields, target teardown, real inventory reward and partial claims.');
const { createRemotes, encodeState } = await import('./net.js');
const remotes = createRemotes();
remotes.apply({ t: 'join', player: { pid: 'p', state: { p: [0, 0, 0], layer: 'world' } } }, 0);
remotes.apply({ t: 'state', pid: 'p', p: [50, 5, 50], layer: 'oldcellars:3' }, 1);
assert.equal(remotes.get('p').layer, 'oldcellars:3');
assert.equal(remotes.get('p').samples.length, 1, 'no interpolation through unrelated floors');
assert.equal(encodeState({ layer: 'oldcellars:8' }).layer, 'oldcellars:8');
