import assert from 'node:assert/strict';
import {makeDom} from './editor/test_dom.mjs';
import {buildTalentPanel} from './talent_panel.js';
import {planCharacter} from './creation.js';
import {grantExperience,talentRank} from '../mmo/talents.js';
const dom=makeDom(),create=dom.createElement;
dom.createElement=tag=>{const el=create(tag);el.append=(...children)=>children.forEach(c=>el.appendChild(c));return el;};
globalThis.document=dom;
const c=planCharacter({opening:'mage',name:'Tester'}).character;
const el=dom.createElement('div'),events=[];
const ctx={character:c,abilities:{applyPassives:()=>events.push('passives')},state:{touch:k=>events.push(k)},recompute:()=>events.push('recompute'),hud:{unlock:a=>events.push(a.id),log:t=>events.push(t)},audio:{play:c=>events.push(c)}};
let picked=null;
const panel=buildTalentPanel(el,ctx,{artSvg:a=>a.id,setBarSlot:()=>({ok:true,reason:'placed'}),pick:(id,place)=>{picked={id,place};}});
const all=n=>[n,...n.children.flatMap(all)];
const byClass=cls=>all(el).filter(n=>n.classList.contains(cls));
assert.equal(byClass('talent-branch').length,3);
assert.ok(el.textContent.includes('Level 1'));assert.ok(el.textContent.includes('0 talent points available'));
const fire=byClass('talent-node').find(n=>n.textContent.includes('Fireball'));
const learn=all(fire).find(n=>n.classList.contains('talent-learn'));
assert.equal(learn.disabled,true);learn.fire('click');assert.equal(talentRank(c,'fireball'),0,'handler also enforces points');
grantExperience(c,100);panel.refresh();assert.equal(learn.disabled,false);learn.fire('click');
assert.equal(talentRank(c,'fireball'),1);assert.ok(events.includes('advancement'));assert.ok(events.includes('passives'));assert.ok(events.includes('recompute'));assert.ok(events.includes('fireball'));
learn.fire('click');assert.equal(talentRank(c,'fireball'),1,'no second spend');
all(fire).find(n=>n.classList.contains('talent-icon')).fire('click');assert.equal(picked.id,'fireball');picked.place(0);assert.ok(events.includes('bar'));
const rogue=all(el).find(n=>n.tagName==='BUTTON'&&n.textContent==='Rogue');rogue.fire('click');assert.equal(byClass('talent-branch').length,3);assert.ok(el.textContent.includes('Assassination'));
console.log('Talent panel interaction checks passed.');
