import assert from 'node:assert/strict';
import {makeDom} from './editor/test_dom.mjs';
import {buildTalentPanel} from './talent_panel.js';
import {planCharacter} from './creation.js';
import {grantExperience,talentRank} from '../mmo/talents.js';
const dom=makeDom();globalThis.document=dom;
const c=planCharacter({opening:'mage',name:'Tester'}).character;
const el=dom.createElement('div'),events=[];
const ctx={character:c,abilities:{applyPassives:()=>events.push('passives')},state:{touch:k=>events.push(k)},recompute:()=>events.push('recompute'),hud:{unlock:a=>events.push(a.id),log:t=>events.push(t)},audio:{play:c=>events.push(c)}};
let picked=null;
const panel=buildTalentPanel(el,ctx,{artSvg:a=>a.id,setBarSlot:()=>({ok:true,reason:'placed'}),pick:(id,place)=>{picked={id,place};}});
const all=n=>[n,...n.children.flatMap(all)];
const byClass=cls=>all(el).filter(n=>n.classList.contains(cls));
const button=text=>all(el).find(n=>n.tagName==='BUTTON'&&n.textContent===text);
const card=id=>byClass('talent-node').find(n=>n.dataset.nodeId===id);
assert.equal(byClass('talent-branch').length,3);assert.equal(byClass('talent-node').length,36);
assert.ok(el.textContent.includes('Level 1'));assert.ok(el.textContent.includes('0 talent points available'));
const fire=card('mage.fire.fireball');all(fire).find(n=>n.classList.contains('talent-icon')).fire('click');
let learn=byClass('talent-detail-learn')[0];assert.equal(learn.disabled,true);learn.fire('click');assert.equal(talentRank(c,'fireball'),0,'handler enforces points');
panel.refresh();assert.equal(byClass('talent-detail-learn')[0],learn,'unchanged refresh preserves focused controls');
grantExperience(c,100);panel.refresh();learn=byClass('talent-detail-learn')[0];assert.equal(learn.disabled,false);learn.fire('click');
assert.equal(talentRank(c,'fireball'),1);assert.ok(events.includes('advancement'));assert.ok(events.includes('passives'));assert.ok(events.includes('recompute'));assert.ok(events.includes('fireball'));
byClass('talent-detail-learn')[0].fire('click');assert.equal(talentRank(c,'fireball'),1,'no second spend');
button('Place on action bar').fire('click');assert.equal(picked.id,'fireball');picked.place(0);assert.ok(events.includes('bar'));
const saved=JSON.stringify(c.advancement),future=card('mage.fire.kindling');all(future).find(n=>n.classList.contains('talent-icon')).fire('click');
assert.equal(byClass('talent-detail-learn').length,0,'planned talents have no purchase control');assert.ok(byClass('talent-details')[0].textContent.includes('Planned'));
assert.equal(JSON.stringify(c.advancement),saved);
button('Hide planned talents').fire('click');assert.ok(byClass('talent-node').length<36);assert.equal(byClass('talent-future-label').length,0);
button('Rogue').fire('click');assert.equal(byClass('talent-branch').length,3);assert.ok(el.textContent.includes('Assassination'));
const knife=card('rogue.combat.throwingKnife');all(knife).find(n=>n.classList.contains('talent-icon')).fire('click');
assert.equal(byClass('talent-detail-learn')[0].disabled,true);byClass('talent-detail-learn')[0].fire('click');assert.equal(JSON.stringify(c.advancement),saved,'browsing another class cannot spend or learn');
assert.ok(byClass('talent-connections').some(n=>n.innerHTML.includes('<path')),'prerequisite paths render');
console.log('Talent panel interaction checks passed.');
