// Live, original specialization modifiers. Effects are data for the shared
// runtime reader; per-rank values are expressed exactly once here.
const effect = (type, changes, abilityIds, when) => ({ type, ...(abilityIds ? { abilityIds: Array.isArray(abilityIds) ? abilityIds : [abilityIds] } : {}), changes, ...(when ? { when } : {}) });
const ability = (abilityIds, changes, when) => effect('ability', changes, abilityIds, when);
const actor = (changes, when) => effect('actor', changes, null, when);
const summon = (abilityIds, changes, when) => effect('summon', changes, abilityIds, when);
const m = (id, name, effects, requires = [], level = null, requiredTreePoints = null) => ({ id, name, kind: 'modifier', status: 'live', maxRank: 3, pointCost: 1, effects, requires, ...(level ? { level } : {}), ...(requiredTreePoints ? { requiredTreePoints } : {}) });
const c = (id, name, effects) => ({ id, name, kind: 'modifier', status: 'live', maxRank: 1, pointCost: 1, level: 82, requiredTreePoints: 25, capstone: true, effects, requires: [] });
const dot = abilityId => ({ kind: 'ownDot', abilityId });
const below = { kind: 'targetBelowHalf' };
const shield = { kind: 'hasShield' };
const rooted = { kind: 'targetControlled' };
const hidden = { kind: 'selfEffect', abilityId: 'hide' };
const berserk = { kind: 'selfEffect', abilityId: 'berserk' };
const evasion = { kind: 'selfEffect', abilityId: 'evasion' };
const manaShield = { kind: 'selfEffect', abilityId: 'manaShield' };
const consecrate = { kind: 'selfEffect', abilityId: 'consecrateWeapon' };
const all = (...conditions) => ({ kind: 'all', conditions });

export const MODIFIERS = {
  'mage.arcane': [
    m('copperThread', 'Copper thread', [ability('magicArrow', { damagePct: .03 })]),
    m('measuredBreath', 'Measured breath', [ability('magicArrow', { costPct: -.03 })]),
    m('longSpark', 'Long spark', [ability('lightning', { rangeFlat: .5 })]),
    m('looseCircuit', 'Loose circuit', [ability('lightning', { costPct: -.03 })]),
    m('thinStep', 'Thin step', [ability('blink', { moveDistanceFlat: .4 })]),
    m('runeWick', 'Rune wick', [ability('manaShield', { durationPct: .05 })]),
    m('forkedNeedle', 'Forked needle', [ability('chainLightning', { damagePct: .03 })]),
    m('greenGlass', 'Green glass', [actor({ spellCrit: .005 })], ['arcaneMastery']),
    m('closedCurrent', 'Closed current', [ability('lightning', { damagePct: .04 }, manaShield)], ['manaShield'], 50, 15),
    c('copperStorm', 'Copper storm', [ability('chainLightning', { damagePct: .15 }, manaShield), ability('chainLightning', { costPct: .1 })]),
  ],
  'mage.fire': [
    m('emberThread', 'Ember thread', [ability('fireball', { dotDamagePct: .03 })]),
    m('dryKindling', 'Dry kindling', [ability('fireball', { costPct: -.03 })]),
    m('kilnMouth', 'Kiln mouth', [ability('fireball', { rangeFlat: .5 })]),
    m('slowCoal', 'Slow coal', [ability('fireball', { durationPct: .05 })]),
    m('cinderScatter', 'Cinder scatter', [ability('spellPlague', { radiusFlat: .2 })]),
    m('coalLens', 'Coal lens', [ability('meteor', { damagePct: .03 })]),
    m('smokeRoad', 'Smoke road', [ability('fireball', { castTimePct: -.03 })]),
    m('blackBell', 'Black bell', [ability('meteor', { costPct: -.03 })]),
    m('bankedHeat', 'Banked heat', [ability('fireball', { damagePct: .04 }, dot('fireball'))]),
    c('kilnWake', 'Kiln wake', [ability('meteor', { damagePct: .15 }, dot('fireball'))]),
  ],
  'mage.frost': [
    m('hailEdge', 'Hail edge', [ability('iceShard', { damagePct: .03 })]),
    m('coldPalm', 'Cold palm', [ability('iceShard', { costPct: -.03 })]),
    m('longWinter', 'Long winter', [ability('frostNova', { controlDurationFlat: .1 })]),
    m('thinIce', 'Thin ice', [ability('iceShard', { slowFractionFlat: .02 })]),
    m('rimeShelter', 'Rime shelter', [ability('stoneSkin', { durationPct: .05 })]),
    m('clearBank', 'Clear bank', [ability('ward', { radiusFlat: .2 })]),
    m('driftingMist', 'Drifting mist', [ability('iceShard', { rangeFlat: .5 })]),
    m('whiteFoot', 'White foot', [actor({ runSpeed: .005 })]),
    m('splinterWindow', 'Splinter window', [ability('iceShard', { damagePct: .04 }, rooted)]),
    c('stillWater', 'Still water', [ability('iceShard', { damagePct: .15 }, rooted), ability('iceShard', { costPct: .1 })]),
  ],
  'warrior.arms': [
    m('sawtoothEdge', 'Sawtooth edge', [ability('rend', { dotDamagePct: .03 })]),
    m('balancedHaft', 'Balanced haft', [ability('powerStrike', { costPct: -.03 })]),
    m('longMeasure', 'Long measure', [ability('lunge', { moveDistanceFlat: .3 })]),
    m('lastingCut', 'Lasting cut', [ability('rend', { durationPct: .05 })]),
    m('hammerDebt', 'Hammer debt', [ability('crushingBlow', { damagePct: .03 })]),
    m('broadIron', 'Broad iron', [ability('sweep', { radiusFlat: .2 })]),
    m('sureFooting', 'Sure footing', [actor({ armourRatingFlat: 3 })]),
    m('temperedGrip', 'Tempered grip', [ability('crushingBlow', { costPct: -.03 })]),
    m('redLedger', 'Red ledger', [ability('powerStrike', { damagePct: .04 }, dot('rend'))], ['rend'], 50, 15),
    c('woundReckoning', 'Wound reckoning', [ability('powerStrike', { damagePct: .15 }, dot('rend')), ability('powerStrike', { costPct: .1 })]),
  ],
  'warrior.fury': [
    m('millWheel', 'Mill wheel', [ability('whirlwind', { damagePct: .03 })]),
    m('deepBreath', 'Deep breath', [ability('whirlwind', { costPct: -.03 })]),
    m('wideCircle', 'Wide circle', [ability('whirlwind', { radiusFlat: .2 })]),
    m('roughChorus', 'Rough chorus', [ability('battleCry', { durationPct: .05 })]),
    m('hotIron', 'Hot iron', [ability('berserk', { durationPct: .03 })]),
    m('runningWrath', 'Running wrath', [actor({ runSpeed: .005 })]),
    m('bitterReserve', 'Bitter reserve', [actor({ armourRatingFlat: 3 })]),
    m('hardCadence', 'Hard cadence', [ability('powerStrike', { costPct: -.03 })]),
    m('redWeather', 'Red weather', [ability('whirlwind', { damagePct: .04 }, berserk)]),
    c('furnaceTurn', 'Furnace turn', [ability('whirlwind', { damagePct: .15 }, berserk), ability('whirlwind', { costPct: .1 })]),
  ],
  'warrior.protection': [
    m('rivetFace', 'Rivet face', [ability('shieldBash', { damagePct: .03 })]),
    m('easyGuard', 'Easy guard', [ability('shieldBash', { costPct: -.03 })]),
    m('heavyRim', 'Heavy rim', [ability('shieldBash', { controlDurationFlat: .1 })]),
    m('brokenGrip', 'Broken grip', [ability('disarm', { durationPct: .05 })]),
    m('groundClaim', 'Ground claim', [ability('leapSlam', { radiusFlat: .2 })]),
    m('shortLanding', 'Short landing', [ability('leapSlam', { costPct: -.03 })]),
    m('layeredIron', 'Layered iron', [actor({ armourRatingFlat: 3 })]),
    m('returningSteel', 'Returning steel', [actor({ parryCounterMult: .02 })], ['riposte']),
    m('lowGuard', 'Low guard', [ability('shieldBash', { damagePct: .04 }, { kind: 'selfBelowHalf' })]),
    c('lastRivet', 'Last rivet', [actor({ armourRatingFlat: 15 }, all({ kind: 'selfBelowHalf' }, shield))]),
  ],
  'rogue.assassination': [
    m('fineIncision', 'Fine incision', [ability('deepCut', { dotDamagePct: .03 })]),
    m('lightWrist', 'Light wrist', [ability('dualStrike', { costPct: -.03 })]),
    m('longWound', 'Long wound', [ability('deepCut', { durationPct: .05 })]),
    m('bitterCoating', 'Bitter coating', [ability('deepCut', { costPct: -.03 })]),
    m('quietPressure', 'Quiet pressure', [ability('kidneyShot', { controlDurationFlat: .1 })]),
    m('closingKnife', 'Closing knife', [ability('finishingStrike', { damagePct: .03 })]),
    m('smallTarget', 'Small target', [actor({ armourRatingFlat: 3 })]),
    m('lastBreath', 'Last breath', [ability('finishingStrike', { costPct: -.03 })]),
    m('bleedingMargin', 'Bleeding margin', [ability('finishingStrike', { damagePct: .04 }, dot('deepCut'))]),
    c('finalIncision', 'Final incision', [ability('finishingStrike', { damagePct: .15 }, dot('deepCut')), ability('finishingStrike', { costPct: .1 })]),
  ],
  'rogue.combat': [
    m('flyingEdge', 'Flying edge', [ability('throwingKnife', { damagePct: .03 })]),
    m('spareMotion', 'Spare motion', [ability('throwingKnife', { costPct: -.03 })]),
    m('longThrow', 'Long throw', [ability('throwingKnife', { rangeFlat: .5 })]),
    m('narrowEscape', 'Narrow escape', [ability('evasion', { durationPct: .1 })]),
    m('openSeam', 'Open seam', [ability('exposeWeakness', { markBonusFlat: .01 })]),
    m('patientReading', 'Patient reading', [ability('exposeWeakness', { durationPct: .05 })]),
    m('streetFooting', 'Street footing', [actor({ runSpeed: .005 })]),
    m('toughStitching', 'Tough stitching', [actor({ armourRatingFlat: 3 })]),
    m('knifeRhythm', 'Knife rhythm', [ability('dualStrike', { damagePct: .04 }, evasion)]),
    c('crowdedDoorway', 'Crowded doorway', [ability('dualStrike', { damagePct: .15 }, evasion), ability('dualStrike', { costPct: .1 })]),
  ],
  'rogue.subtlety': [
    m('darkPoint', 'Dark point', [ability('backstab', { damagePct: .03 })]),
    m('softHand', 'Soft hand', [ability('backstab', { costPct: -.03 })]),
    m('longShadow', 'Long shadow', [ability('shadowstep', { moveDistanceFlat: .3 })]),
    m('patientPocket', 'Patient pocket', [ability('pickPocket', { cooldownPct: -.02 })]),
    m('foldedRoad', 'Folded road', [ability('shadowstep', { costPct: -.03 })]),
    m('quietReturn', 'Quiet return', [ability('vanish', { cooldownPct: -.02 })]),
    m('softSoles', 'Soft soles', [actor({ runSpeed: .005 })]),
    m('smokeLining', 'Smoke lining', [actor({ armourRatingFlat: 3 })]),
    m('unseenEdge', 'Unseen edge', [ability('backstab', { damagePct: .04 }, hidden)]),
    c('emptyDoorway', 'Empty doorway', [ability('backstab', { damagePct: .15 }, hidden), ability('backstab', { costPct: .1 })]),
  ],
  'ranger.marksmanship': [
    m('trueGrain', 'True grain', [ability('aimedShot', { damagePct: .03 })]),
    m('smoothDraw', 'Smooth draw', [ability('aimedShot', { costPct: -.03 })]),
    m('farNotch', 'Far notch', [ability('aimedShot', { rangeFlat: .5 })]),
    m('twinFletch', 'Twin fletch', [ability('doubleShot', { damagePct: .03 })]),
    m('leanQuiver', 'Lean quiver', [ability('doubleShot', { costPct: -.03 })]),
    m('narrowShaft', 'Narrow shaft', [ability('piercingArrow', { damagePct: .03 })]),
    m('broadRain', 'Broad rain', [ability('volley', { radiusFlat: .2 })]),
    m('dryString', 'Dry string', [ability('volley', { costPct: -.03 })]),
    m('closingDistance', 'Closing distance', [ability('piercingArrow', { damagePct: .04 }, below)]),
    c('cleanLine', 'Clean line', [ability('aimedShot', { damagePct: .15 }, below), ability('aimedShot', { castTimePct: .1 })]),
  ],
  'ranger.survival': [
    m('tightLoop', 'Tight loop', [ability('snare', { controlDurationFlat: .1 })]),
    m('quickKnot', 'Quick knot', [ability('snare', { castTimePct: -.03 })]),
    m('leanWire', 'Lean wire', [ability('snare', { costPct: -.03 })]),
    m('barbedBolt', 'Barbed bolt', [ability('cripplingShot', { damagePct: .03 })]),
    m('draggingTrail', 'Dragging trail', [ability('cripplingShot', { slowFractionFlat: .02 })]),
    m('backwardBound', 'Backward bound', [ability('disengage', { moveDistanceFlat: .3 })]),
    m('spareBreath', 'Spare breath', [ability('disengage', { costPct: -.03 })]),
    m('trailLegs', 'Trail legs', [actor({ runSpeed: .005 })]),
    m('heldQuarry', 'Held quarry', [ability('cripplingShot', { damagePct: .04 }, rooted)]),
    c('briarAnswer', 'Briar answer', [ability('cripplingShot', { damagePct: .15 }, rooted), ability('cripplingShot', { costPct: .1 })]),
  ],
  'ranger.beastmastery': [
    m('longCalling', 'Long calling', [summon('beastCall', { durationPct: .05 })]),
    m('familiarWhistle', 'Familiar whistle', [ability('beastCall', { costPct: -.03 })]),
    m('answeringHills', 'Answering hills', [ability('beastCall', { cooldownPct: -.02 })]),
    m('fedCompanion', 'Fed companion', [summon('beastCall', { healthPct: .04 })]),
    m('sharpCompanion', 'Sharp companion', [summon('beastCall', { damagePct: .03 })]),
    m('lastingScent', 'Lasting scent', [ability('huntersMark', { durationPct: .05 })]),
    m('clearScent', 'Clear scent', [ability('huntersMark', { markBonusFlat: .01 })]),
    m('sharedTrail', 'Shared trail', [actor({ runSpeed: .005 })], ['fleetFoot']),
    m('patientTending', 'Patient tending', [ability('bandage', { healingPct: .04 })]),
    c('twoShadows', 'Two shadows', [summon('beastCall', { damagePct: .15 }, { kind: 'ownerMark', abilityId: 'huntersMark' })]),
  ],
  'paladin.holy': [
    m('openHand', 'Open hand', [ability('heal', { healingPct: .04 })]),
    m('smallPrayer', 'Small prayer', [ability('heal', { costPct: -.03 })]),
    m('farMercy', 'Far mercy', [ability('heal', { rangeFlat: .5 })]),
    m('deepWell', 'Deep well', [ability('greaterHeal', { healingPct: .04 })]),
    m('steadyWords', 'Steady words', [ability('greaterHeal', { castTimePct: -.03 })]),
    m('cleanCloth', 'Clean cloth', [ability('cleanse', { costPct: -.03 })]),
    m('lastKindness', 'Last kindness', [ability('layOnHands', { cooldownPct: -.02 })]),
    m('strongVessel', 'Strong vessel', [actor({ armourRatingFlat: 3 })]),
    m('woundedWelcome', 'Wounded welcome', [ability('heal', { healingPct: .04 }, below)]),
    c('shelterInTheWound', 'Shelter in the wound', [ability('heal', { healingPct: .15 }, below), ability('heal', { costPct: .1 })]),
  ],
  'paladin.protection': [
    m('brassAnswer', 'Brass answer', [ability('shieldBash', { damagePct: .03 })]),
    m('lightBurden', 'Light burden', [ability('shieldBash', { costPct: -.03 })]),
    m('patientBlessing', 'Patient blessing', [ability('bless', { durationPct: .05 })]),
    m('heldGround', 'Held ground', [ability('ward', { durationPct: .05 })]),
    m('broadShelter', 'Broad shelter', [ability('ward', { radiusFlat: .2 })]),
    m('leanVigil', 'Lean vigil', [ability('ward', { costPct: -.03 })]),
    m('layeredOath', 'Layered oath', [actor({ armourRatingFlat: 3 })]),
    m('quietThreshold', 'Quiet threshold', [ability('sanctuary', { cooldownPct: -.02 })]),
    m('firmReply', 'Firm reply', [ability('shieldBash', { damagePct: .04 }, shield)]),
    c('stoneVow', 'Stone vow', [actor({ armourRatingFlat: 15 }, all(shield, { kind: 'selfEffect', abilityId: 'ward' }))]),
  ],
  'paladin.retribution': [
    m('oathEdge', 'Oath edge', [ability('powerStrike', { damagePct: .03 })]),
    m('lightGrip', 'Light grip', [ability('powerStrike', { costPct: -.03 })]),
    m('longEmber', 'Long ember', [ability('consecrateWeapon', { durationPct: .05 })]),
    m('clearSentence', 'Clear sentence', [ability('smite', { damagePct: .03 })]),
    m('shortPrayer', 'Short prayer', [ability('smite', { costPct: -.03 })]),
    m('carryingVoice', 'Carrying voice', [ability('battleCry', { durationPct: .05 })]),
    m('heavyAnswer', 'Heavy answer', [ability('crushingBlow', { damagePct: .03 })]),
    m('roadIron', 'Road iron', [actor({ armourRatingFlat: 3 })]),
    m('burningOath', 'Burning oath', [ability('powerStrike', { damagePct: .04 }, consecrate)]),
    c('ashenOath', 'Ashen oath', [ability('powerStrike', { damagePct: .15 }, consecrate), ability('powerStrike', { costPct: .1 })]),
  ],
  'priest.holy': [
    m('gentleThread', 'Gentle thread', [ability('heal', { healingPct: .04 })]),
    m('thinCandle', 'Thin candle', [ability('heal', { costPct: -.03 })]),
    m('reachingHands', 'Reaching hands', [ability('heal', { rangeFlat: .5 })]),
    m('deepStitch', 'Deep stitch', [ability('greaterHeal', { healingPct: .04 })]),
    m('unhurriedBreath', 'Unhurried breath', [ability('greaterHeal', { castTimePct: -.03 })]),
    m('clearWater', 'Clear water', [ability('cleanse', { costPct: -.03 })]),
    m('returningVoice', 'Returning voice', [ability('resurrect', { castTimePct: -.03 })]),
    m('lastCandle', 'Last candle', [ability('layOnHands', { cooldownPct: -.02 })]),
    m('quietHands', 'Quiet hands', [ability('greaterHeal', { healingPct: .04 }, below)]),
    c('mendingDusk', 'Mending dusk', [ability('greaterHeal', { healingPct: .15 }, below), ability('greaterHeal', { costPct: .1 })]),
  ],
  'priest.discipline': [
    m('straightWord', 'Straight word', [ability('smite', { damagePct: .03 })]),
    m('measuredWord', 'Measured word', [ability('smite', { costPct: -.03 })]),
    m('heldLight', 'Held light', [ability('bless', { durationPct: .05 })]),
    m('wovenShelter', 'Woven shelter', [ability('ward', { durationPct: .05 })]),
    m('widerShelter', 'Wider shelter', [ability('ward', { radiusFlat: .2 })]),
    m('closeWeave', 'Close weave', [ability('manaShield', { absorbEfficiencyPct: .05 })]),
    m('quietReserve', 'Quiet reserve', [ability('manaShield', { costPct: -.03 })]),
    m('lastRefuge', 'Last refuge', [ability('sanctuary', { cooldownPct: -.02 })]),
    m('guardedAnswer', 'Guarded answer', [ability('smite', { damagePct: .04 }, manaShield)]),
    c('lightUnderPressure', 'Light under pressure', [ability('smite', { damagePct: .15 }, manaShield), ability('smite', { costPct: .1 })]),
  ],
  'priest.shadow': [
    m('hollowNeedle', 'Hollow needle', [ability('eldritchBolt', { damagePct: .03 })]),
    m('emptyBreath', 'Empty breath', [ability('eldritchBolt', { costPct: -.03 })]),
    m('longHunger', 'Long hunger', [ability('lifeDrain', { rangeFlat: .5 })]),
    m('deepHunger', 'Deep hunger', [ability('lifeDrain', { damagePct: .03 })]),
    m('patientBurden', 'Patient burden', [ability('curseOfWeakness', { durationPct: .05 })]),
    m('distantDread', 'Distant dread', [ability('fear', { radiusFlat: .2 })]),
    m('paleSpear', 'Pale spear', [ability('boneSpear', { damagePct: .03 })]),
    m('spreadingHush', 'Spreading hush', [ability('spellPlague', { radiusFlat: .2 })]),
    m('fadingPulse', 'Fading pulse', [ability('lifeDrain', { damagePct: .04 }, below)]),
    c('hollowRefrain', 'Hollow refrain', [ability('lifeDrain', { leechFractionFlat: .15 }, below)]),
  ],
};
