// Persistence for hand-placed scenery.
//
// The landmark models and the scenery forests are generated by the theme, which
// means a reload — or any code edit — regenerates them and throws away whatever
// you arranged by hand. This store keeps those edits in localStorage, keyed by
// theme, and the generators consult it as they build, so a hand-placed layout
// survives reloads and hot updates until it is explicitly reset.

const KEY = (theme) => `nostrux-scenery-${theme}`;

let themeId = 'default';
export function setSceneryTheme(id) { themeId = id || 'default'; }
export function sceneryTheme() { return themeId; }

export function loadStore() {
  try { return JSON.parse(localStorage.getItem(KEY(themeId)) || '{}'); } catch { return {}; }
}

export function saveStore(store) {
  try { localStorage.setItem(KEY(themeId), JSON.stringify(store)); } catch {}
}

export function patchStore(fn) {
  const store = loadStore();
  fn(store);
  saveStore(store);
}

// Forget every hand placement for this theme and fall back to what the theme
// generates. Callers reload/rebuild the scene afterwards.
export function clearStore() {
  try { localStorage.removeItem(KEY(themeId)); } catch {}
}

export function storeSummary() {
  const s = loadStore();
  return {
    theme: themeId,
    landmarks: Object.keys(s.landmarks || {}).length,
    treeFields: Object.keys(s.trees || {}).length,
    trees: Object.values(s.trees || {}).reduce((n, list) => n + (list?.length || 0), 0),
  };
}
