// Persistence for hand-placed scenery.
//
// The landmark models and the scenery forests are generated by the theme, which
// means a reload — or any code edit — regenerates them and throws away whatever
// you arranged by hand. This store keeps those edits in localStorage, keyed by
// theme, and the generators consult it as they build, so a hand-placed layout
// survives reloads and hot updates until it is explicitly reset.

const KEY = (theme) => `nostrux-scenery-${theme}`;

// A theme's shipped layout. localStorage (a test-mode hand edit) layers on top,
// so players get the authored zone while it stays tweakable in the editor.
const baselines = {};
export function registerBaseline(theme, data) { baselines[theme] = data; }

let themeId = 'default';
export function setSceneryTheme(id) { themeId = id || 'default'; }
export function sceneryTheme() { return themeId; }

// the raw per-browser edits only — what patchStore writes back
function loadSaved() {
  try { return JSON.parse(localStorage.getItem(KEY(themeId)) || '{}'); } catch { return {}; }
}

// the shipped layout with any hand edits layered over it
export function loadStore() {
  const base = baselines[themeId] || {};
  const saved = loadSaved();
  return {
    landmarks: { ...(base.landmarks || {}), ...(saved.landmarks || {}) },
    extras: saved.extras || base.extras || [],
    trees: { ...(base.trees || {}), ...(saved.trees || {}) },
  };
}

export function saveStore(store) {
  try { localStorage.setItem(KEY(themeId), JSON.stringify(store)); } catch {}
}

// edits are written to the browser's own layer, never merged back into the
// shipped baseline
export function patchStore(fn) {
  const saved = loadSaved();
  fn(saved);
  saveStore(saved);
}

// Forget every hand placement for this theme and fall back to what the theme
// generates. Callers reload/rebuild the scene afterwards.
export function clearStore() {
  try { localStorage.removeItem(KEY(themeId)); } catch {}
}

export function storeSummary() {
  const s = loadStore();
  const own = loadSaved();
  return {
    theme: themeId,
    handEdits: Object.keys(own.landmarks || {}).length + (own.extras || []).length
      + ((own.trees || {})[Object.keys(own.trees || {})[0]] ? 1 : 0),
    landmarks: Object.keys(s.landmarks || {}).length,
    treeFields: Object.keys(s.trees || {}).length,
    trees: Object.values(s.trees || {}).reduce((n, list) => n + (list?.length || 0), 0),
  };
}
