// Authored stopping places and habitat edges, in world metres. Every tuple is
// deliberate. Effects and animals share the exact same centres as their props.
const p=(model,x,z,yaw=0,scale=1)=>({model:'lw_'+model,x,z,yaw,scale});
const fx=(id,x=0,z=0,gate='always',scale=1,y=0)=>({id,x,z,gate,scale,y});
const animal=(id,x,z,clip='idle',yaw=0)=>({id,x,z,clip,yaw});
const forage=(id,x,z,count=2)=>({id,x,z,count});
const h=(id,zone,name,x,z,note,pieces=[],extra={})=>({id:'greenwold_habitat_'+id,zone,name,at:{x,z},note,radius:42,pieces,...extra});
export const HABITATS=[
 h('orchard_yard','hearthhome','The orchard yard',501,-167,'Apple trees shelter the washing line behind the inn.',[p('apple_tree',-6,0),p('apple_tree',7,3),p('washing_line',0,8),p('rain_barrel',-4,8),p('chicken_coop',7,11),p('lantern_post',-3,-5)],{lights:[{x:-3,z:-5,y:2.5,color:0xffc083,power:20,range:14}],effects:[fx('drifting_petals',-6,0,'day')],animals:[animal('cat',-3,11,'stretch'),animal('chicken',6,15,'peck'),animal('chicken',10,14,'peck',140)]}),
 h('west_gate_work','hearthhome','The wood yard',381,-211,'Split logs wait outside the village gate, where carts can turn.',[p('woodpile',0,0),p('chopping_block',4,3),p('log_pile',-7,3),p('cow_parsley',-6,9)],{effects:[fx('floating_seeds',-6,9,'day')]}),
 h('mill_lane_fold','longmeadow','The shepherds fold',143,-235,'A shepherd keeps the flock in the lee of the long grassy bank.',[p('shepherds_hut',0,0,90),p('cattle_trough',8,4),p('hay_wain',-8,1),p('cowslip_patch',-9,-10)],{pad:10,animals:[animal('sheep',6,10,'graze',40),animal('sheep',10,12,'graze',220)],effects:[fx('butterflies',-9,-10,'fair')]}),
 h('meadow_hay','longmeadow','The hay cutting',-309,-410,'The hay cart stands on the headland beside the cut field.',[p('hay_wain',0,0,65),p('plough',5,3,40),p('harrow',-5,3),p('poppy_patch',-9,9),p('cow_parsley',7,9)],{forage:[forage('wild_strawberry',-5,11)],effects:[fx('floating_seeds',-9,9,'fair')]}),
 h('hay_lane_warren','longmeadow','The rabbit bank',-614,-498,'Rabbits have opened the dry bank above the haymakers lane.',[p('rabbit_warren',0,0),p('hawthorn',8,3),p('bramble_thicket',-6,4),p('molehills',0,8)],{pad:21,forage:[forage('blackberry',-7,8)],effects:[fx('butterflies',8,5,'fair')]}),
 h('mill_store','millrun','The mill stores',-1019,-321,'Flour and spare millstones stand beside the granary, above the wet bank.',[p('flour_sacks',0,0),p('millstones',-6,0),p('woodpile',-6,5)],{animals:[animal('mill_cart_horse',4,1,'idle',90)]}),
 h('mill_bank','millrun','The mill bank',-987,-283,'A heron watches the shallows below the mill willows.',[p('yellow_iris',0,0),p('rushes',-6,3),p('mooring_post',5,0)],{animals:[animal('heron',2,3,'idle',130)],effects:[fx('fireflies',-6,3,'night')]}),
 h('wood_entrance','beechhangar','The wood entrance',-1111,-177,'Coppiced stools and stacked timber mark the change from mill lane to working wood.',[p('coppice_stool',-7,0),p('log_pile',0,0),p('bracken',0,8),p('foxglove',7,8)],{effects:[fx('falling_leaves',0,5,'always',1.5)]}),
 h('charcoal','beechhangar','The charcoal clearing',-1135,-20,'A charcoal clamp smoulders in a clearing off the hollow way. Cut poles wait beside the hut.',[p('charcoal_clamp',0,0),p('woodcutters_hut',12,0,90),p('log_pile',0,10),p('coppice_stool',-10,10),p('chopping_block',10,10)],{pad:30,effects:[fx('chimney_smoke',0,0,'always',.75,1.5)],forage:[forage('oyster_mushroom',-12,15)]}),
 h('fern_hollow','beechhangar','The fern hollow',-1118,119,'Ferns crowd the damp side of the hollow way. Edible shoots grow beside the bank.',[p('bracken',0,0),p('bracken',-5,4,35),p('ivy_stump',5,6),p('leaf_litter',0,10)],{forage:[forage('fiddlehead',4,11),forage('wild_garlic',-7,10)],effects:[fx('woodland_shafts',0,5,'fair',1.6),fx('fireflies',-5,4,'night',1.5)]}),
 h('hidden_cache','beechhangar','The hunters shelter',-958,207,'A hunter left supplies beneath the beech ridge. Dogs prowl the approach after dark.',[p('hunters_seat',0,0),p('deer_rub',-6,3),p('bracken',5,7),{model:'loot_sack',x:3,z:2,yaw:0}],{forage:[forage('chanterelle',-3,7)],spawns:[{id:'wildDog',x:11,z:13,night:true},{id:'wildDog',x:17,z:9,night:true}],effects:[fx('mushroom_spores',-3,7,'night')]}),
 h('beech_floor','beechhangar','The bluebell bank',-1053,342,'Bluebells grow above the badger setts; the open path stays beneath them.',[p('bluebell_patch',0,0),p('foxglove',7,3),p('bracken',-7,4)],{effects:[fx('pollen_motes',0,0,'fair'),fx('fireflies',0,0,'night',1.7)]}),
 h('quarry_track','chalkpits','The quarry layby',-998,-553,'Pit timber is stacked in the layby below the chalk climb.',[p('log_pile',0,0),p('timber_prop',7,0),p('flint_nodules',-6,4),p('gorse',5,9)],{pad:22,effects:[fx('dust_gust',0,3,'fair',.7)]}),
 h('chalk_spur','chalkpits','The white spur',-788,-846,'A pale outcrop shows where the quarry road turns beneath the ridge.',[p('chalk_boulder',0,0),p('chalk_boulder',8,-5,45,.8),p('flint_nodules',3,7),p('gorse',-7,6)]),
 h('chalk_beacon','chalkpits','The pit beacon',-565,-1152,'A brazier marks the rim above the last switchback.',[p('beacon_brazier',0,0),p('chalk_boulder',5,3),p('gorse',-6,4)],{pad:15,effects:[fx('watch_fire',0,0,'night',.65,1.3)],lights:[{x:0,z:0,y:2.1,color:0xffb971,power:18,range:14}]}),
 h('pilgrims_rest','standinghedge','The pilgrims rest',90,-733,'A cairn marks the descent from the mere toward the standing stones.',[p('cairn',0,0),p('hawthorn',-7,3),p('cowslip_patch',5,6)],{forage:[forage('rosehip',-7,8)],effects:[fx('fireflies',5,6,'night')]}),
 h('mere_shore','sunkenchapel','The drowned boundary',-145,-840,'A broken boundary wall and rushes follow the shore beside the causeway.',[p('drowned_wall',0,0),p('rushes',6,3),p('yellow_iris',-5,5)],{effects:[fx('mist_bank',0,4,'night',1.6)]}),
 h('chapel_wake','sunkenchapel','The chapel graves',-40,-962,'Cold motes hang beside the outer graves after sunset.',[p('ivy_stump',0,0),p('rushes',-3,6)],{effects:[fx('mist_bank',-3,2,'night',1.5),fx('fireflies',0,0,'night',.8)],lights:[{x:0,z:0,y:.8,color:0x79abc2,power:5,range:11}]}),
 h('mere_path_hide','highwaymanshollow','The bramble turn',295,-1008,'Bramble closes around a turn in the path. The clearing beyond holds an outlaw watch.',[p('bramble_thicket',-5,0),p('dead_oak',5,4),p('stolen_goods',0,7)],{spawns:[{id:'bandit',x:6,z:12}],forage:[forage('blackberry',-7,4)]}),
 h('hollow_stores','highwaymanshollow','The stolen stores',524,-1010,'Goods taken from the road are stacked behind the tents.',[p('stolen_goods',0,0),p('woodpile',-5,5),p('wanted_poster',5,4)]),
 h('hollow_fire','highwaymanshollow','The hollow fire',497.87,-1019.39,'The outlaws keep their fire inside the bowl of the camp.',[],{effects:[fx('watch_fire',0,0,'always',.8,.3)],lights:[{x:0,z:0,y:1.5,color:0xff964a,power:24,range:17}]}),
 h('hollow_rear','highwaymanshollow','The hidden pack',449,-877,'A pack lies in the blackberries beside the rear approach. Its owners watch from the bank.',[p('bramble_thicket',0,0),{model:'loot_sack',x:4,z:4,yaw:0},p('ivy_stump',-5,4)],{spawns:[{id:'goblinScout',x:-7,z:12,night:true}],forage:[forage('blackberry',3,8)]}),
 h('legion_supply','kingsroad','The Legion supply stop',941,-1032,'The tithe wagon waits behind the road watch, beside stacked provisions.',[p('tithe_wagon',0,0,130),p('legion_barrier',7,4,130),p('woodpile',-7,3)]),
 h('legion_fire','kingsroad','The road watchfire',944.09,-1069.91,'The watch brazier lights the tents without lighting the whole hillside.',[],{effects:[fx('watch_fire',0,0,'night',.6,1.3)],lights:[{x:0,z:0,y:2,color:0xffc083,power:23,range:18}]}),
 h('kingsroad_hedge','kingsroad','The road shoulders',672,-735,'Thorn and gorse hold the banks beside the paved road.',[p('hawthorn',0,0),p('gorse',-8,-3),p('cow_parsley',-7,5)],{forage:[forage('rosehip',-5,10)],effects:[fx('floating_seeds',-7,5,'fair')]}),
 h('cellar_bank','oldcellars','The guarded cutting',93,-151,'Cut logs and a lantern mark the guarded side of the cellar cutting.',[p('log_pile',0,0),p('lantern_post',5,3),p('ivy_stump',-5,6)],{lights:[{x:5,z:3,y:2.5,color:0xffb974,power:16,range:12}]}),
 h('towpath_willows','watermeadows','The towpath willows',-322,-10,'Iris and reeds gather beneath the willows along the wet towpath.',[p('yellow_iris',0,0),p('rushes',-6,3),p('pollard_willow',6,5)],{animals:[animal('dragonfly',0,3,'hover')],effects:[fx('fireflies',0,0,'night',1.3)],forage:[forage('nettle',-6,8)]}),
 h('water_bank','watermeadows','The reed margin',-602,12,'Reeds follow the inside bend, with open ground left beside the crossing.',[p('rushes',0,0),p('yellow_iris',6,4),p('pollard_willow',-7,4)],{animals:[animal('heron',4,7,'idle',240)],effects:[fx('mist_bank',0,3,'night',1.2)]}),
 h('drovers_rest','coldwake','The drovers halt',-547,469,'A trough and hay wagon offer a halt between the river and the southern ridge.',[p('cattle_trough',0,0),p('hay_wain',-7,2),p('hawthorn',6,6)],{animals:[animal('cow',-3,7,'graze')],effects:[fx('floating_seeds',5,5,'fair')]}),
 h('south_wood','coldwake','The bridleway coppice',-847,677,'Coppice stools and a saw pit occupy a working clearing beside the bridleway.',[p('saw_pit',0,0),p('log_pile',8,2),p('coppice_stool',-7,4)],{pad:22,effects:[fx('falling_leaves',-7,4)],forage:[forage('oyster_mushroom',8,8)]}),
 h('coldwake_orchard','coldwake','The Coldwake orchard',-431,802,'An orchard and a small duck pond lie behind the cottages.',[p('apple_tree',-7,0),p('apple_tree',7,3),p('duck_pond',0,10),p('washing_line',-8,10),p('lantern_post',-1,-7)],{lights:[{x:-1,z:-7,y:2.5,color:0xffc083,power:20,range:14}],effects:[fx('drifting_petals',7,3,'day')],animals:[animal('cat',-4,10,'idle'),animal('duck',-1,12,'idle',100),animal('duck',2,11,'idle',230)],forage:[forage('wild_strawberry',8,9)]}),
 h('south_fields','standinghedge','The high pasture',-158,590,'Sheep graze the sheltered side of the southern folds, above the lane to the stones.',[p('gorse',-7,0),p('cattle_trough',0,0),p('cowslip_patch',7,4)],{animals:[animal('sheep',-3,8,'graze'),animal('sheep',5,10,'graze',170)],effects:[fx('butterflies',7,4,'fair')]}),
 h('stone_north','standinghedge','The northern stone bank',475,-617,'Thorn and fern frame the northern stone without crowding its face.',[p('hawthorn',8,0),p('bracken',-7,3),p('ivy_stump',0,5)],{effects:[fx('fireflies',0,3,'night',1.5)]}),
 h('stone_east','standinghedge','The eastern stone hollow',739,-337,'A fern-lined hollow interrupts the walk between the eastern stones.',[p('bracken',-6,0),p('foxglove',6,4),p('dead_oak',0,8)],{effects:[fx('fireflies',0,0,'night')],forage:[forage('chanterelle',-7,6)]}),
 h('stone_south','standinghedge','The southern thorn bank',470,193,'Wildflowers follow the sheltered edge of the southern stone lane.',[p('cowslip_patch',0,0),p('hawthorn',7,4),p('cow_parsley',-7,3)],{effects:[fx('butterflies',0,0,'fair')],forage:[forage('dandelion',-7,7)]}),
 h('stone_west','standinghedge','The western fern bank',-150,-294,'Beeches close around the west lane. Ferns soften the foot of the bank.',[p('bracken',-2,0),p('foxglove',6,4),p('ivy_stump',6,-4)],{effects:[fx('falling_leaves',0,0),fx('fireflies',0,0,'night')],forage:[forage('wild_garlic',4,8)]}),
 ];
// Short, named footpaths into the eight banks that cannot be entered directly.
// Their road mouths are measured points on the authored main routes.
const APPROACHES={
 hay_lane_warren:[-607.4,-465.6],charcoal:[-1102.4,-14],hidden_cache:[-942.5,197.2],
 quarry_track:[-964.5,-563.1],chalk_spur:[-769.2,-797.2],chalk_beacon:[-547,-1159],
 cellar_bank:[57.9,-139.6],south_wood:[-837.7,666.7],
};
for(const h of HABITATS){const point=APPROACHES[h.id.slice(18)];if(point)h.approach=point;}
