import assert from 'node:assert/strict';
import {cameraBodyFraction} from './camera.js';
import {createCollisionIndex} from './shapes.js';
const from={x:0,y:2,z:0},to={x:0,y:2,z:10};
const box={kind:'box',x:0,y:0,z:5,w:4,d:.01,h:4,c:1,s:0};
const distance=b=>createCollisionIndex(b).cameraDistance(from,to,.3);
assert.equal(distance([]),10,'Open space must retain full distance');
assert(Math.abs(distance([box])-4.695)<1e-9,'Thin wall was skipped');
assert.equal(distance([{...box,enabled:()=>false}]),10,'Inactive collision should release');
assert.equal(distance([{...box,x:4}]),10,'A wall beside a clear path should not obstruct');
assert(distance([{...box,w:8,c:Math.SQRT1_2,s:Math.SQRT1_2}])<5,'Rotated wall was skipped');
assert.equal(distance([{...box,y:3}]),10,'A high lintel must leave its doorway open');
assert(distance([{...box,y:1.8,h:.15}])<5,'Low gallery ceiling was skipped');
assert(distance([{...box,x:2.2}])<5,'The near-plane edge must not enter the corner');
assert.equal(distance([{...box,x:2.4}]),10,'Corner clearance should not seal an open path');
assert.equal(cameraBodyFraction(box,{x:0,y:2,z:5},to,.3),0,'Inside-wall camera must retract');
const circle={kind:'circle',x:0,y:0,z:5,h:4,r:.2};
assert.equal(distance([circle]),4.5);
assert.equal(distance([{...circle,x:1}]),10);
const ramp={kind:'ramp',x:0,y:0,z:5,w:4,d:4,h:4,c:1,s:0,direction:1,thickness:.4};
const cast=(a,b)=>createCollisionIndex([ramp]).cameraDistance(a,b,.28);
assert(cast({x:0,y:5,z:5},{x:0,y:0,z:5})<3,'Ramp deck should stop descending camera');
assert(cast({x:0,y:0,z:5},{x:0,y:5,z:5})<2,'Ramp underside should stop rising camera');
assert.equal(cast({x:0,y:0,z:4},{x:0,y:0,z:6}),2,'Thin ramps must leave usable space underneath');
const reversed={...ramp,direction:-1};
assert.notEqual(cameraBodyFraction(ramp,{x:0,y:5,z:4},{x:0,y:0,z:4},.28),cameraBodyFraction(reversed,{x:0,y:5,z:4},{x:0,y:0,z:4},.28));
console.log('CAMERA_SWEEP_VERIFIED');
