import assert from 'node:assert/strict';
import * as T from 'three';
import {prepareCameraMesh} from './camera-mesh.js';
import {createRoomArtwork} from '../../game/streaming/room_artwork.js';
const work={run:async fn=>fn()},group=new T.Group();
const wall=new T.Mesh(new T.PlaneGeometry(4,4),new T.MeshBasicMaterial());wall.position.set(0,2,5);group.add(wall);
const obstacle=await prepareCameraMesh(group,{work});obstacle.update();
const from={x:0,y:2,z:0},to={x:0,y:2,z:10};
assert(Math.abs(obstacle.distance(from,to,.28,10)-4.72)<1e-8,'Thin front face missed');
assert(Math.abs(obstacle.distance(to,from,.28,10)-4.72)<1e-8,'Culled back face missed');
assert.equal(obstacle.distance({x:3,y:2,z:0},{x:3,y:2,z:10},.28,10),10,'Clear route should remain clear');
assert(obstacle.distance({x:2.2,y:2,z:0},{x:2.2,y:2,z:10},.28,10)<5,'Near-plane edge clipped the wall edge');
assert(obstacle.distance({x:2.1,y:4.1,z:0},{x:2.1,y:4.1,z:10},.28,10)<5,'Near-plane corner clipped the wall vertex');
assert.equal(obstacle.distance({x:2.3,y:4.3,z:0},{x:2.3,y:4.3,z:10},.28,10),10);
group.position.set(10,0,0);group.scale.setScalar(2);obstacle.update();
assert(Math.abs(obstacle.distance({x:10,y:4,z:0},{x:10,y:4,z:20},.28,20)-9.72)<1e-8,'Instance transform or camera radius scaled incorrectly');
const cancelled=new AbortController();cancelled.abort();
const fresh=new T.Group();fresh.add(new T.Mesh(new T.BoxGeometry(),new T.MeshBasicMaterial()));
assert.equal(await prepareCameraMesh(fresh,{work,signal:cancelled.signal}),null);
const transparent=new T.Group();transparent.add(new T.Mesh(new T.PlaneGeometry(20,20),new T.MeshBasicMaterial({transparent:true,opacity:.3})));
const glow=await prepareCameraMesh(transparent,{work});glow.update();assert.equal(glow.distance(from,to,.28,10),10,'Soft effects should not shove the camera');
const obstacles=new Set(),scene=new T.Scene();
const artwork=createRoomArtwork({id:'camera-fixture',url:'test',load:async()=>({scene:group}),work,cameraObstacles:obstacles,attach:instance=>scene.add(instance.group)});
assert(await artwork.ready);assert.equal(obstacles.size,1,'Loaded room did not publish camera surfaces');
artwork.dispose();assert.equal(obstacles.size,0,'Evicted room left invisible camera blockers');
const sharedGeometry=new T.SphereGeometry(2,64,32),sharedA=new T.Group(),sharedB=new T.Group();
sharedA.add(new T.Mesh(sharedGeometry,new T.MeshBasicMaterial()));sharedB.add(new T.Mesh(sharedGeometry,new T.MeshBasicMaterial()));
let chunks=0;const counted={run:async fn=>{chunks++;return fn();}};
await Promise.all([prepareCameraMesh(sharedA,{work:counted}),prepareCameraMesh(sharedB,{work:counted})]);
assert.equal(chunks,Math.ceil(sharedGeometry.index.count/3072),'Concurrent room instances rebuilt the same camera index');
sharedGeometry.dispose();for(const root of [sharedA,sharedB])root.children[0].material.dispose();
for(const root of [group,fresh,transparent])root.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});
console.log('CAMERA_MESH_VERIFIED');
