import { escapeHtml as e, storyHtml } from './content.mjs';
import { sharedRealmArt } from './art.mjs';
import { art, cover, shell, sidebar, nextChapter, realmHref, placeHref, kindLabel, biomeLabel } from './layout.mjs';

export function atlasPage(lore, assets) {
  const cards = lore.realms.map(realm => `<a class="realm-card" href="${realmHref(realm)}">${art(realm.id, realm.name)}<div class="realm-card-copy"><div class="card-heading"><span class="chapter-number">${String(realm.chapter).padStart(2, '0')}</span><span class="section-label">${e(biomeLabel(realm.biome))}</span></div><h3>${e(realm.name)}</h3><p>${e(realm.line)}</p><span class="card-link">${realm.places.length} places to discover <span aria-hidden="true">↗</span></span></div></a>`).join('');
  const places = lore.places.map(place => `<li data-place data-search="${e([place.name, place.realmName, place.geography, place.contains, kindLabel(place.kind)].join(' '))}" hidden><a href="/lore/${place.realmId}/${place.id}/">${art(place.id, place.name)}<div class="search-copy"><span class="section-label">${e(place.realmName)} · ${e(kindLabel(place.kind))}</span><h3>${e(place.name)}</h3><p>${e(place.geography)}</p><span class="card-link">Explore this place <span aria-hidden="true">↗</span></span></div></a></li>`).join('');
  const body = `<main id="content">${cover({ id: 'atlas', title: 'Lore and lands', eyebrow: 'The illustrated world of Brackenwake', intro: 'Nine realms. One sea. The last dragon.', after: '<a class="cover-link" href="#realms-title">Explore the atlas <span aria-hidden="true">↓</span></a>', className: 'atlas-cover' })}
<div class="concept-notice"><span aria-hidden="true">✧</span><p>An atlas of a world taking shape. All illustrations are concept art, not gameplay screenshots.</p><a href="/lore/story/">Read the story <span aria-hidden="true">→</span></a></div>
<div class="atlas-content"><section class="atlas-search" hidden><div><label for="lore-search">Where will you wander?</label><p id="search-help">${lore.places.length} places across ${lore.realms.length} realms.</p></div><div class="search-field"><input id="lore-search" type="search" placeholder="Find a place, person or landscape…" autocomplete="off" aria-describedby="search-help"><p id="search-status" role="status" aria-live="polite"></p></div></section>
<section id="search-results" hidden aria-label="Matching places"><ul class="place-results">${places}</ul><p id="search-empty" hidden>No places found. Try another name or landscape.</p></section>
<section id="realm-list" aria-labelledby="realms-title"><div class="section-heading"><div><p class="eyebrow">Around the Caldera Sea</p><h2 id="realms-title">Choose a realm</h2></div><span>${lore.realms.length} chapters of the world</span></div><div class="realm-grid">${cards}</div></section></div></main>`;
  return shell({ title: 'Lore and lands', description: `Explore Brackenwake’s ${lore.realms.length} realms and ${lore.places.length} named places through illustrated concept art and world lore.`, path: '/lore/', body, current: 'atlas', assets, index: true });
}

function placeArticle(place, realm) {
  const regional = !!sharedRealmArt[place.id];
  return `<article class="place${regional ? ' place--regional' : ''}" id="${place.id}">${regional ? '' : `<a class="place-art-link" href="${placeHref(realm, place)}" aria-label="Explore ${e(place.name)}">${art(place.id, place.name)}</a>`}<div class="place-copy"><p class="place-kind">${e(kindLabel(place.kind))}</p><h3><a href="${placeHref(realm, place)}">${e(place.name)}</a></h3><p>${e(place.geography)}</p><p class="discoveries">${e(place.contains)}</p>${place.levels || place.boss ? `<p class="place-notes">${place.levels ? `${place.levels} dungeon levels` : ''}${place.levels && place.boss ? ' · ' : ''}${place.boss ? `Boss: ${e(place.boss)}` : ''}</p>` : ''}${place.mechanic ? `<details class="place-detail"><summary>A planned rule of this place</summary><p>${e(place.mechanic)}</p></details>` : ''}<a class="text-link" href="${placeHref(realm, place)}">Explore this place <span aria-hidden="true">↗</span></a></div></article>`;
}

export function realmPage(realm, lore, assets) {
  const next = lore.realms[realm.chapter % lore.realms.length];
  const encounterPlace = realm.places.find(place => place.kind === 'wild') || realm.places.at(-1);
  const storyPlace = realm.places[0];
  const body = `<main id="content">${cover({ id: realm.id, title: realm.name, eyebrow: `Chapter ${String(realm.chapter).padStart(2, '0')} · ${biomeLabel(realm.biome)}`, intro: realm.line, breadcrumb: '<a href="/lore/">World atlas</a><span aria-hidden="true">/</span><span>The realms</span>' })}
<div class="reading-layout">${sidebar(lore, realm.id, realm.places)}<div class="realm-content"><nav class="chapter-nav" aria-label="In this realm"><a href="#landscape">The landscape</a><a href="#places">${realm.places.length} places</a><a href="#encounters">Encounters</a><a href="#story">Story and people</a></nav>
<section id="landscape" class="reading-section landscape-section"><p class="eyebrow">A sense of place</p><h2>The landscape</h2><p class="geography">${e(realm.geography)}</p><div class="landmark"><p class="section-label">On the horizon</p><p>${e(realm.mega)}</p></div></section>
<section id="places" class="reading-section"><div class="section-heading"><div><p class="eyebrow">The paths within</p><h2>Places in ${e(realm.name.replace(/^The /, 'the '))}</h2></div><span>${realm.places.length} places</span></div><div class="places">${realm.places.filter(place => !sharedRealmArt[place.id]).map(place => placeArticle(place, realm)).join('')}</div>${realm.places.some(place => sharedRealmArt[place.id]) ? `<div class="regional-places">${realm.places.filter(place => sharedRealmArt[place.id]).map(place => placeArticle(place, realm)).join('')}</div>` : ''}</section>
<section id="encounters" class="reading-section illustrated-section">${art(encounterPlace.id, encounterPlace.name)}<div><p class="eyebrow">Out on the road</p><h2>Encounters and events</h2><ul class="encounters">${realm.encounters.map(encounter => `<li>${e(encounter)}</li>`).join('')}</ul><p class="development-note">From the world plans. Encounters and events may change during development.</p></div></section>
<section id="story" class="reading-section">${art(storyPlace.id, storyPlace.name, { className: 'story-section-art' })}<p class="eyebrow">Lives woven through the land</p><h2>Story and people</h2><p class="story-intro">The characters, secrets and dragon’s journey through ${e(realm.name.replace(/^The /, 'the '))}.</p><details class="story-book"><summary><span>Read the story outline</span><small>Contains story spoilers</small></summary><div class="prose">${realm.story.map(block => `<section><h3>${e(block.title)}</h3>${storyHtml(block.body)}</section>`).join('')}</div></details></section>${nextChapter(next)}</div></div></main>`;
  return shell({ title: realm.name, description: realm.line, path: realmHref(realm), body, current: realm.id, assets, image: realm.id });
}

export function storyPage(lore, assets) {
  const body = `<main id="content">${cover({ id: 'last-dragon', title: 'The last dragon', eyebrow: 'The Dragonsworn', intro: 'The last egg is the one that hatched on your arm this morning.', breadcrumb: '<a href="/lore/">World atlas</a><span aria-hidden="true">/</span><span>The story</span>' })}<div class="reading-layout">${sidebar(lore, '')}<article class="realm-content story-page"><p class="development-note">An illustrated story in development. These images are concept art.</p><div class="prose opening-story">${storyHtml(lore.premise)}<section><h2>The dragon beside you</h2>${storyHtml(lore.dragon)}</section><section>${art('the-bond', 'the Bond between a traveler and their dragon')}<p class="eyebrow">A soul shared willingly</p><h2>The Bond</h2>${storyHtml('The Bond ' + lore.bond)}</section><section>${art('wyrmsoul', 'Wyrmsoul')}<p class="eyebrow">Two lives, one fire</p><h2>Wyrmsoul</h2>${storyHtml(lore.wyrmsoul)}</section></div>${nextChapter(lore.realms[0], 'The first chapter')}</article></div></main>`;
  return shell({ title: 'The last dragon', description: 'The Dragonsworn, the last dragon, and the pact that binds them. Illustrated story concepts for Brackenwake.', path: '/lore/story/', body, current: 'story', assets, image: 'last-dragon' });
}
