// Explicit QA-only character; this page cannot read or write real saved players.
const memory=new Map(),storage={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,String(v)),removeItem:k=>memory.delete(k),clear:()=>memory.clear(),key:i=>[...memory.keys()][i]??null,get length(){return memory.size;}};
Object.defineProperty(window,'localStorage',{value:storage});Object.defineProperty(window,'sessionStorage',{value:storage});
const errors=[],status=document.querySelector('#review-status');
addEventListener('error',e=>errors.push(e.message));addEventListener('unhandledrejection',e=>errors.push(String(e.reason)));
const report=async data=>{status.textContent=data.stage;document.title=`Progression: ${data.stage}`;await fetch('http://127.0.0.1:5318/report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,errors})}).catch(()=>{});};
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const wait=async fn=>{const until=performance.now()+150000;while(!fn()){if(performance.now()>until)throw Error('Progression QA timed out');await delay(60);}};
try{
 await report({stage:'progression-loading'});await import('/src/game/main.js');await wait(()=>document.querySelector('[data-opening="mage"]'));
 const creationClasses=[...document.querySelectorAll('[data-opening]')].map(el=>el.dataset.opening);
 if(!['mage','warrior','rogue','ranger','paladin','priest'].every(id=>creationClasses.includes(id)))throw Error('Six classes missing from creation');
 await report({stage:'creation-ready',classes:creationClasses});
 if(new URLSearchParams(location.search).has('creationOnly'))await new Promise(()=>{});
 const reviewClass=new URLSearchParams(location.search).get('characterReview');
 document.querySelector(`[data-opening="${creationClasses.includes(reviewClass)?reviewClass:'mage'}"]`).click();const name=document.querySelector('input[placeholder="a name"]');name.value='Talent review';name.dispatchEvent(new Event('input',{bubbles:true}));
 [...document.querySelectorAll('button')].find(b=>/create character/i.test(b.textContent)).click();await wait(()=>window.__bw?.player);
 const b=window.__bw;b.actor.godMode=true;b.windows.closeAll();await b.runtime.ready;
 const c=b.state.character;
 if(reviewClass){
   b.windows.open('character');await delay(700);
   const {watchCharacterLayout}=await import('./character-layout-checks.js');
   watchCharacterLayout(report);await new Promise(()=>{});
 }
 const {levelOf,talentRank,availablePoints}=await import('/src/mmo/talents.js');
 const initial={level:levelOf(c),bar:[...c.bar],points:availablePoints(c)};
 b.windows.open('abilities');await delay(600);
 const tree=document.querySelector('.bw-talents');if(!tree)throw Error('Skill tree did not render');
 const fire=()=>[...tree.querySelectorAll('.talent-node')].find(n=>n.querySelector('.talent-name')?.textContent==='Fireball');
 const gate=b.abilities.useById('meteor',performance.now()/1000);
 if(talentRank(c,'meteor') || gate?.ok)throw Error('Advanced ability bypassed learning');
 // Defeat an ordinary encounter through the real combat resolver.
 const mon=b.monsters.spawnEncounter('wolf',b.player.pos.x+1,b.player.pos.z+1);
 if(!mon)throw Error('Could not create QA combatant');
 const xpBefore=c.advancement.xp;b.combat.hurt(mon.actor,100000,{now:performance.now(),killer:b.actor});await delay(150);
 if(c.advancement.xp<=xpBefore)throw Error('Real monster defeat awarded no XP');
 const earnedXp=c.advancement.xp-xpBefore;
 const corpse=b.monsters.corpses().find(x=>x.actor===mon.actor);if(!corpse?.loot)throw Error('Monster did not keep loot on its corpse');
 const dropped=b.loot.count,corpseItems=corpse.loot.items.length,corpseGold=corpse.loot.gold;
 b.levels.award(100-c.advancement.xp);await delay(650);fire().querySelector('.talent-icon').click();tree.querySelector('.talent-detail-learn').click();await delay(100);
 if(talentRank(c,'fireball')!==1 || availablePoints(c)!==0)throw Error('Learning did not consume exactly one point');
 const {setBarSlot}=await import('/src/game/win_abilities.js');setBarSlot(c,3,'fireball');b.state.touch('bar');b.state.save();
 const {hydrate}=await import('/src/game/state.js');const round=hydrate(JSON.parse(JSON.stringify(c)));
 if(talentRank(round,'fireball')!==1 || levelOf(round)!==2 || round.bar[3]!=='fireball')throw Error('Save round trip lost progression');
 const {SLOTS:slots,makeItem}=await import('/src/mmo/items.js');
 b.windows.open('character');await delay(300);
 const gearSlots=[...document.querySelectorAll('.bw-doll-slot[data-slot]')].map(n=>n.dataset.slot);
 if(slots.some(slot=>gearSlots.filter(s=>s===slot).length!==1))throw Error('Equipment HUD is missing or duplicating slots');
 const beforeAr=b.actor.ar,oldChest=c.equipment.chest;
 if(!b.inventory.unequip('chest').ok || !(b.actor.ar<beforeAr))throw Error('Removing chest armor did not change armor rating');
 const chestIndex=c.pack.items.indexOf(oldChest);
 if(!b.inventory.equip(chestIndex,'chest').ok || b.actor.ar!==beforeAr)throw Error('Equipping chest armor did not restore armor rating');
 const savedGear=hydrate(JSON.parse(JSON.stringify(c))).equipment;
 if(slots.some(slot=>savedGear[slot]?.id!==c.equipment[slot]?.id))throw Error('Equipment save round trip lost an item');
 b.windows.open('corpseLoot',{corpse});await delay(100);
 const goldBefore=c.gold,claimIds=corpse.loot.items.map(i=>i.id);
 const takeAll=[...document.querySelectorAll('.bw-corpse-loot button')].find(button=>button.textContent==='Take all');
 if(!takeAll)throw Error('Corpse loot HUD did not render');takeAll.click();
 if(c.gold!==goldBefore+corpseGold || b.corpseLoot.hasLoot(corpse) || claimIds.some(id=>!c.pack.items.some(i=>i?.id===id)))throw Error('Loot HUD did not transfer corpse rewards');
 if(b.corpseLoot.takeAll(corpse).ok || c.gold!==goldBefore+corpseGold)throw Error('Repeated corpse claim duplicated loot');
 const equipmentVerified={slots:gearSlots,armorBefore:beforeAr,armorAfter:b.actor.ar,saved:true};
 const lootVerified={items:claimIds.length,gold:corpseGold,duplicateRefused:true};
 await report({stage:'progression-verified',initial,level:levelOf(c),points:availablePoints(c),fireballRank:talentRank(c,'fireball'),xpFromKill:earnedXp,slots,gearSlots,corpseItems,corpseGold,floorDrops:dropped,equipmentVerified,lootVerified,shaderErrors:b.sc.renderer.info.programs.filter(p=>p.diagnostics?.runnable===false).length});
 const {verifyLiveTalents}=await import('./live-talents.js');await verifyLiveTalents(b,report);
 const previewCorpse={name:'Wolf',pos:b.player.pos,active:true,loot:{items:[makeItem({base:'rapier',seed:981})],gold:24}};
 window.__progressionReview={b,c,corpse,tree:()=>b.windows.open('abilities'),gear:()=>b.windows.open('character'),loot:()=>b.windows.open('corpseLoot',{corpse:previewCorpse}),report};
 const controls=document.createElement('nav');controls.id='review-controls';controls.setAttribute('aria-label','QA review panels');
 controls.style.cssText='position:fixed;right:12px;bottom:8px;z-index:999999;display:flex;gap:6px';
 for(const [label,action] of [['Review trees','tree'],['Review equipment','gear'],['Review loot','loot']]){const button=document.createElement('button');button.textContent=label;button.style.cssText='padding:8px;background:#19241f;color:#f0dfae;border:1px solid #a68b45;border-radius:4px';button.addEventListener('click',()=>window.__progressionReview[action]());controls.appendChild(button);}document.body.appendChild(controls);
 b.windows.open('abilities');await report({stage:'progression-ready'});
}catch(error){await report({stage:'progression-failed',error:String(error),stack:error.stack});}
