import assert from 'node:assert/strict';
import {planCharacter} from '../creation.js';
import {playerActor,spawnMonster} from '../actor.js';
import {createCombat,SWING_LAND_S} from '../combat.js';
import {swingSeconds} from '../../mmo/combat_rules.js';
import {ABILITIES_BY_ID} from '../../mmo/abilities.js';
import {MONSTERS} from '../../mmo/monsters.js';
import {createAbilities} from '../abilities_runtime.js';
const player=playerActor(planCharacter({opening:'warrior',name:'Pace test'}).character),enemy=spawnMonster('wolf');
player.lastSwingAt=-Infinity;player.pos={x:0,y:0,z:0};enemy.pos={x:0,y:0,z:1};enemy.health=enemy.maxHealth=1e6;
const combat=createCombat({rng:()=>0}),events=[];let procs=0;
combat.onStrike(e=>events.push(e));combat.onHit(()=>procs++);
const interval=swingSeconds(player)*1000;
assert.ok(interval>=550&&interval<=1400);assert.equal(SWING_LAND_S,.3);
assert.equal(combat.queueSwing(player,enemy,{now:0}).queued,true);
for(let now=1;now<=100;now++)assert.equal(combat.queueSwing(player,enemy,{now}).queued,false);
combat.update(.299,299);assert.equal(events.length,0);assert.equal(enemy.health,1e6);
combat.update(.001,300);assert.equal(events.length,1);assert.ok(enemy.health<1e6);assert.equal(procs,0,'ordinary strikes do not masquerade as item procs');
assert.equal(combat.queueSwing(player,enemy,{now:interval-1}).queued,false);
assert.equal(combat.queueSwing(player,enemy,{now:interval}).queued,true);
enemy.pos.z=100;combat.update(.4,interval+400);assert.equal(events.length,1,'an out-of-reach swing has no impact event');
for(const row of Object.values(MONSTERS))assert.equal(row.hp,row.tier===0?row.baseHp:Math.round(row.baseHp*1.5),row.id);
assert.equal(ABILITIES_BY_ID.fireball.castTime,.35);assert.equal(ABILITIES_BY_ID.iceShard.castTime,.35);assert.equal(ABILITIES_BY_ID.heal.castTime,.45);
console.log(JSON.stringify({starterSwingMs:interval,impactMs:300,spamRefused:100,hitEvents:events.length,procEvents:procs}));
const c=planCharacter({opening:'mage',name:'Cast test'}).character,caster=playerActor(c),target=spawnMonster('wolf');
caster.pos={x:0,y:0,z:0};target.pos={x:0,y:0,z:5};c.skills.magery=100;
const hits=createCombat({rng:()=>.5}),bolts=[];
const spells=createAbilities({character:c,actor:caster,player:{pos:caster.pos,yaw:0,speed:0},combat:hits,monsters:{targets:()=>[target]},rng:()=>.99,effects:{bolt:(from,to,colour,opts)=>bolts.push(opts.onArrive)}});
const mana=caster.mana,hp=target.health,cast=spells.useById('fireball',10);assert.equal(cast.ok,true,cast.reason);assert.equal(cast.record.castTime,.35);
assert.equal(caster.mana,mana-9);assert.equal(spells.useById('fireball',10.1).ok,false);assert.equal(caster.mana,mana-9,'a refused repeat does not pay twice');
spells.update(.349,10.349);assert.equal(bolts.length,0);assert.equal(target.health,hp);
spells.update(.001,10.35);assert.equal(bolts.length,1,'the real effect dispatches at the shortened release');
hits.update(0,10350);bolts[0]();hits.update(.5,10850);assert.ok(target.health<hp,'the dispatched bolt reaches the real damage resolver');
assert.equal(spells.useById('fireball',12.999).ok,false);assert.equal(spells.useById('fireball',13).ok,true);
console.log(JSON.stringify({fireballReleaseMs:350,manaPaid:9,cooldownSeconds:3,damage:hp-target.health}));
